version: 2 # CircleCI version
jobs:
    build:
        machine: true # Use a Linux VM instead of docker environment
        working_directory: ~/repo
        steps:
            - checkout
            - run: ssh -p $PORT $USER@$IP "/bin/bash /home/boxofknowledge/tmp/ReseauEntrepriseB/script/usage.sh"